name: github pages

on:
  push:
    branches:
      - master
  schedule:
  - cron: "0 11,23 * * *"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Pull stats
        run: ./pull_stats.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
